### ISSUE TITLE
Static content serving with independent Docker containers

### ISSUE THREAD

**Issue by florian-lerch** [oasp/my-thai-star#119]
**Category:** help wanted
**Severity:** Medium

**Description of issue / expected enhancement /Comments**
The Java and Angular parts have been built in separate pipelines. Then, independent Docker containers are built. In contrast to the Wiki article (https://github.com/oasp/my-thai-star/wiki/deployment-strategies), the files are not copied into already running nginx/tomcat servers, but Docker images are built already containing the application files. Thereby, we can handle the containers as immutable.
We use a reverse-proxy and a Docker network, the application is accessed via port 8080.

The Dockerfile for the Java part is:
```
FROM tomcat:latest
COPY /mtsj/server/target/mythaistar.war /usr/local/tomcat/webapps/
EXPOSE 8080
```

The Dockerfile for Angular is:
```
FROM nginx:latest
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    apache2-utils \
    && rm -rf /var/lib/apt/lists/*
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY /dist/* /usr/share/nginx/html/
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
```
**Expected behaviour:**
All images are displayed.
**Actual behaviour:**
Some images are missing.
Menu cannot be loaded.

**Possible source of problem:**
Images use paths like
`src="../../assets/images/thai-restaurant.jpg"`
There are no more two directories above after deploying the war file. Therefore, the specified path cannot be found.

**Your environment - windows/Linux, Devonfw version , component**
Windows 7 64-bit, Chrome 67.0.3396.87 & Firefox 60.0.2 (64-Bit)

Website with the original path. The path is ../../ is not available, the image is not shown.
![problematicimage-originalpath](https://user-images.githubusercontent.com/29492792/41859268-25043188-789c-11e8-9bb8-e579cdfed04f.PNG)

Website with path modified. Now, the image can be displayed.
![problematicimage-newpath](https://user-images.githubusercontent.com/29492792/41859307-37538de8-789c-11e8-82a9-802beec63aaf.PNG)

**Comment by cbeldacap** [comment]
Hi @florian-lerch ,

Could you please share the content of the `/usr/share/nginx/html` directory of your front-end container? (the nginx one).

Can't see where the problem comes from so far.

Cheers,
Cristóbal

**Comment by florian-lerch** [comment]
root@our-virtual-machine:~# docker exec -it mts_angular bash
root@b128f3763a5a:/# cd /usr/share/nginx/html
root@b128f3763a5a:/usr/share/nginx/html# ls
50x.html
MaterialIcons-Regular.012cf6a10129e2275d79.woff
MaterialIcons-Regular.570eb83859dc23dd0eec.woff2
MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf
MaterialIcons-Regular.e79bfd88537def476913.eot
Wood2.7b3782e7fd543cc9cdc4.jpg
ad.313cc919c665805590b8.svg
ad.ead7604352750854830d.svg
af.68d6fe6fbb8d26245577.svg
af.da6dc167c9127f158374.svg
ai.867c186790e2d74a2efb.svg
ai.ee6ee9bc23bb863b0d73.svg
as.4c21826658a383cc144a.svg
as.f383cf21ee5ac80f64d4.svg
aw.470237051b8678699cd4.svg
aw.f631ae0a06ec235884e1.svg
background-dish.fe9678cd8802fa639336.png
bm.3c3a4bb2d510ff5ccecb.svg
bm.62e57b0da090af0c9f39.svg
bn.8f92a2a68334a67d2cfb.svg
bn.fbe8d8b29b5d9d1e3b2a.svg
bo.6fb296d5ddde2f98ed23.svg
bo.b867573646ad241e0e82.svg
br.1a59cea1ca6c94fb6c00.svg
br.78de6acf30cc7fa47002.svg
bt.a8c715fb69e0e7a4871f.svg
bt.ba78c82bac7649a0c63c.svg
bz.43b35557c843e5b5b411.svg
bz.54bf457314ccf5c2a7a4.svg
dm.0c25d1c964ee725ee3fb.svg
dm.26eebc61eaf81cade452.svg
do.46ecd3f1009dc727f806.svg
do.b458ed8d22464a6c8ffa.svg
ec.0ccc7990711012699754.svg
ec.a5936cd548051de7f86c.svg
eg.6b3ede5793ddf47b6316.svg
eg.855377c17e85edfbbcce.svg
es.2d0caa1aed39c950dcf3.svg
es.8020fcd82cc09410f7ba.svg
favicon.ico
fj.06a2a0a58e44dcc78ef3.svg
fj.145f6e915d7155aabde5.svg
fk.0346c5086de1ccb53a45.svg
fk.9afe00c857c5319cad44.svg
gb-nir.bca162fd093b9fd677bd.svg
gb-nir.fe3541260952ff0b2468.svg
gb-wls.bcc948923469b70a294a.svg
gb-wls.c62bd08127e9b768f698.svg
gs.57397584b2f61aaac0f9.svg
gs.ffdcf7e8d78e8419706f.svg
gt.4632809044fa0209427b.svg
gt.b484cf21cb05fdd295ba.svg
hr.563d3c098909c8a7a82d.svg
hr.dc70492e6d0c940aa8c8.svg
ht.439ff5b2b8fdf93f21b3.svg
ht.bf2699c766f54a3528b7.svg
i18n
im.063e4f27d4b9ebfe35ab.svg
im.f359e4af84de97a367e8.svg
images
index.html
inline.bundle.js
inline.bundle.js.map
io.60c160193f00355e5048.svg
io.c3a9a34773e5569364ad.svg
ir.58c78eab9893258a3eec.svg
ir.5e7a66fb0660b714f1a4.svg
kh.9e206ef9fe85c4a790f8.svg
kh.f7fb085f68d9a1577ebc.svg
ky.bea1dbdd7aeb69fa91f6.svg
ky.f5d9d8099bfa0afa1bfd.svg
kz.0e744e4eb3a9efbb061a.svg
kz.63392ec44b380a66d0a2.svg
li.5c6e91bd4340ba0cf51e.svg
li.963c7aa5c1065663ac2a.svg
lk.9822728dbbd634e839cf.svg
lk.f4106211fb7b6945992a.svg
main.bundle.js
main.bundle.js.map
md.63f49a6086369c674c45.svg
md.bba429bfd66b68572749.svg
me.0456e73c5126fc222cbb.svg
me.dadc0f0c71a322e3a86d.svg
mp.9f377cb996052eee3e51.svg
mp.bc3b5c5f5f13fa0f533f.svg
mt.326058406d58b7bff47f.svg
mt.d6eccaefeabe5a23ea03.svg
mx.2101146e7a1d0058002b.svg
mx.98615f7ff2fd0a45e20a.svg
ni.5006277c81e04188e12e.svg
ni.5830a76a5a18a4213e01.svg
om.2ebf43af103747c3fe80.svg
om.f7223881f778b5cf0699.svg
pe.ee097e5092024ddecf50.svg
pe.f0816c3791b8a179e60e.svg
pn.011983ac981416a246e1.svg
pn.e56155c19e2ef1686be7.svg
polyfills.bundle.js
polyfills.bundle.js.map
pt.3c410042f938c619c2a9.svg
pt.492042709de1d5a439aa.svg
py.9303013528a69bc83087.svg
py.b79561133db5b7e34df7.svg
rs.4eaf546a6aa3a57426ca.svg
rs.9926aca85269f2fb4adf.svg
sa.6cc2f890489cf9d91aaf.svg
sa.d2578130afbcef1f2b9f.svg
scripts.bundle.js
scripts.bundle.js.map
sh.2c0e7a98cc7a08a3d05b.svg
sh.db2ed663a84b5352efe9.svg
slider-1.a66518ca4fb732b07a90.jpg
slider-2.824fc6c25bbd8ce09d01.jpg
sm.6b9322fe38345236c244.svg
sm.c1143f65d5a699bc3a2c.svg
star.5cbbb1d4fad2e640a5bb.png
styles.bundle.js
styles.bundle.js.map
sv.3079f878814feec05959.svg
sv.d634f9a62464280ad55f.svg
sx.1fc55ded843b07c6a120.svg
sx.cb86d088b9f7f56bc59e.svg
tc.8f88612b4aece8d809cd.svg
tc.d8595b0311b0908b6e88.svg
tm.8e52383f0c611e135b73.svg
tm.ebbd1999c6b153ee4fc2.svg
un.055d2421a497f11c838b.svg
un.cd3d61b637da2319e2f1.svg
va.6542983178f95bd9b95c.svg
va.ccbda5d3825e050f97bd.svg
vg.0c6aa7d2f5b21f353be3.svg
vg.42724b9781dece199ef7.svg
vi.77f0687e785991234457.svg
vi.7f8aaadbad1ef31f37e2.svg
zw.0db27ac5ee6250bc53eb.svg
zw.363a3e2a9c323bf3030b.svg

**Comment by cbeldacap** [comment]
Hi @florian-lerch ,

In order to reproduce your issue, I think we can discuss it via Skype and then add the conclusions on this thread.

Cheers,
Cristóbal

**Comment by cbeldacap** [comment]
I've proposed @florian-lerch to update his fork's Angular version to the current one (1.6.0).

It could be interesting to update the status in here 👍

**Comment by florian-lerch** [comment]
I've not updated my fork to the latest version yet, but resolved the issue in a different way.

**The error was in our customized Dockerfile for Angular, we changed line 7 from**
```
COPY /dist/* /usr/share/nginx/html/
```

to
```
COPY dist/. /usr/share/nginx/html
```
Now, all images are displayed and the menu can be loaded.

Issue resolved. Thanks for your help, Cristóbal!
