### ISSUE TITLE
Configuration 'proxy.conf.json' could not be found

### ISSUE THREAD

**Issue by denniseffing** [oasp/my-thai-star#124]
**Category:** Bug

**Severity:** Low

**Expected behaviour:** Frontend should start when running `npm start`.

**Actual/current behaviour:** Frontend start fails with error message `Configuration 'proxy.conf.json' could not be found in project 'my-thai-star'.`

**Steps to reproduce:** Clone repo, cd into angular project directory, run `npm install` and follow up with `npm start`.

**Description of issue/expected enhacement/Comments:**
Angular CLI v6 now follows the more standardized option for parsing CLI arguments: -pc is now the equivalent of -p -c and not --proxy-config.
Change `ng serve --pc proxy.conf.json -o` to `ng serve --proxy-config proxy.conf.json -o`.
See angular/angular-cli#9999 for further details.

**Comment by sjimenez77** [comment]
Hi @denniseffing, the issue is fixed.
