### ISSUE TITLE
Declaration of field visibility in angular components

### ISSUE THREAD

**Issue by tlueecke** [oasp/my-thai-star#16]
In the example application I find quite a lot of public declarations of fields. I am more a friend of encapsulating everything until it is really needed to be exposed, so I am wondering, if there is a particular reasoning behind this? What is our best practice regarding this?

**Comment by dumbNickname** [comment]
Do not know what exactly was the part of code that you looked at, but in case of component classes please be aware that AOT forces variables used in templates to be public (as far as I know). For all the rest I agree that traditional encapsulation rules should apply.

**Comment by maybeec** [comment]
Protocol 26.07

* Change field visibility to be as restrictive as possible (with respect to AOT), i.e. stick to private first.
* We should annotate fields during investigation, why some fields might not be declared private as of AOT or some other technical reason. (provide guidance as a sample application)

**Comment by sjimenez77** [comment]
Hi @tlueecke, @maybeec, 
this issue is possibly solved with this PR https://github.com/oasp/my-thai-star/pull/30. May we close this?

**Comment by sjimenez77** [comment]
This issue was solved with PR #30.

**Comment by anmaso** [comment]
Going through code review I see some public injections for example in `BookTableDialogComponent`, I think this issue should be revisited and document the exception on the manual.
