### ISSUE TITLE
Shared / Core modules missing

### ISSUE THREAD

**Issue by tlueecke** [oasp/my-thai-star#17]
Angular clearly recommends to introduce shared and core modules:

https://angular.io/guide/ngmodule#shared-modules
https://angular.io/guide/ngmodule#the-core-module

Although the covalent module in my-thai-star seems to point in the direction of a shared module, it is not named explicitly as such. In addition we miss something like the Core module, and instead of services like the WindowService or the SnackbarService provided by multiple modules, which is from my point of view not a clean approach.

For me the angular best practices make good sense and we should adopt them or if there are reasons against following that pattern, document them.

**Comment by maybeec** [comment]
Protocol 26.07.

* Follow angular conventions
* Rename covalent module to shared module
* Extract WindowService to core module

**Comment by sjimenez77** [comment]
Hi @tlueecke, @maybeec, 
this issue is possibly solved with this PR https://github.com/oasp/my-thai-star/pull/30. May we close this?

**Comment by sjimenez77** [comment]
This issue was solved with PR #30.
