### ISSUE TITLE
Invalid bean validation

### ISSUE THREAD

**Issue by maybeec** [oasp/my-thai-star#2]
Bean validation does not seem to be implemented so far.
In addition bean validation annotations are specified on entity classes, which should not be the case. In contrary, bean validation should be done on the transport objects.

**Comment by sjimenez77** [comment]
Hi @maybeec, 
this issue is possibly solved with this PR https://github.com/oasp/my-thai-star/pull/28. May we close this?

**Comment by sjimenez77** [comment]
Issue closed since it seems that the PR #28 solved it and there were no more comments.
