### ISSUE TITLE
BookTableService.isEmailValid() redundant?

### ISSUE THREAD

**Issue by tlueecke** [oasp/my-thai-star#20]
To me this seems to be redundant code and instead should be replaced by reusing the EmailValidatorDirective.

**Comment by maybeec** [comment]
Protocol 26.07.

* `EmailValidatorDirective` does not validate the correctness of the domain part of emails
* However, there are two redundant validations (service validation and form validation)

**Comment by sjimenez77** [comment]
Hi @tlueecke, @maybeec, 
this issue is possibly solved with this PR https://github.com/oasp/my-thai-star/pull/30. May we close this?

**Comment by sjimenez77** [comment]
This issue was solved with PR #30.
