### ISSUE TITLE
Invalid database constraint specification

### ISSUE THREAD

**Issue by maybeec** [oasp/my-thai-star#3]
Taking the example of `BookingEntity`, there are several `@NotNull` annotations on fields like `email`. However, there is no database constraint at all assuring, that email is never null, which should be done by `@Column(nullable = false)`.

Take a look also on the other entities. It seems to be a failure in use in several entities.

**Comment by sjimenez77** [comment]
Hi @maybeec, 
this issue is possibly solved with this PR https://github.com/oasp/my-thai-star/pull/27. May we close this?

**Comment by sjimenez77** [comment]
Issue closed since it seems that the PR #27 solved it and there were no more comments.
