### ISSUE TITLE
Accessing the application over URL

### ISSUE THREAD

**Issue by marpuch** [oasp/my-thai-star#41]
When I access the application over http://de-mucdevondepl01:8090 - all works fine. I can see the page and I am redirected to http://de-mucdevondepl01:8090/restaurant.

When I access the application over http://de-mucdevondepl01:8090/restaurant - I see a 404.

**Comment by sjimenez77** [comment]
This issue is related with the server configuration. We are trying to solve it right now. We need to redirect every URL to the entry point of the application, I mean `index.html.`

**Comment by sjimenez77** [comment]
Issue solved. Please, test it and close the issue. Thanks!

**Comment by cbeldacap** [comment]
Some extra configuration has been added to the default **nginx** Docker image we've been using for the Angular deployment.

We followed what Angular recommends to solve those problems with **nginx**
https://angular.io/guide/deployment#production-servers

This is the resultant Docker image
https://hub.docker.com/r/cbelda/nginx-try-files/

**Comment by sjimenez77** [comment]
As there is no more activity and it has been properly tested I close this issue.
