### ISSUE TITLE
Imagemanagement obsolete/incorrect

### ISSUE THREAD

**Issue by maybeec** [oasp/my-thai-star#8]
oasp4j already provides a binary management. You might want to adapt it to also include a name of the binary. However, it specifies how to store binaries in the database correctly with blobs.
The imagemanagement does the same and therefore redundant, but in an incorrect way. It does store images as strings, which is not efficient and should not be a reference solution.

**Comment by sjimenez77** [comment]
Closed since the proposed issue #24 already gathers this problem. The information from this issue has been added to it.
